### ISSUE TITLE
get_data and set_data deprecated

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/collabwrapper#22]
While testing collaboration for an activity this was in the logs

```
1586877470.901248 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/ibiam/Activities/dimensions/collabwrapper.py", line 841, in _received_cb
    self._activity_cb(buddy, msg)
  File "/home/ibiam/Activities/dimensions/collabwrapper.py", line 307, in __received_cb
    data = self.activity.get_data()
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 569, in _unsupported_data_method
    raise RuntimeError('Data access methods are unsupported. '
RuntimeError: Data access methods are unsupported. Use normal Python attributes instead
```
A simple test shows
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import GObject
>>> GObject.GObject.set_data('data')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 569, in _unsupported_data_method
    raise RuntimeError('Data access methods are unsupported. '
RuntimeError: Data access methods are unsupported. Use normal Python attributes instead
>>> 
```

**Comment by quozl** [comment]
Add the get_data and set_data methods to the activity.

**Comment by chimosky** [comment]
I actually thought I'd added them.

**Comment by quozl** [comment]
What gave it away for me was analysis of the traceback;

```log
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/ibiam/Activities/dimensions/collabwrapper.py", line 841, in _received_cb
    self._activity_cb(buddy, msg)
  File "/home/ibiam/Activities/dimensions/collabwrapper.py", line 307, in __received_cb
    data = self.activity.get_data()
```

at this point the call stack seems rational, and is in code we maintain.  The next thing we should expect to see is a File and Line reference to the Activity class, but;

```log
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 569, in _unsupported_data_method
```

suddenly we are in code we don't maintain.  Begs the question of why the call in collabwrapper.py:307 did not enter a method in the Activity with that name, and the most likely conclusion was that there was no such method so a search was made for the same method name in all parent classes.

Oddly, `get_data` and `set_data` remain documented methods of GObject.Object
* https://lazka.github.io/pgi-docs/GObject-2.0/classes/Object.html#GObject.Object
* https://gitlab.gnome.org/GNOME/glib/-/blob/master/gobject/gobject.c

So it is an unnecessary restriction to not only declare the methods as unsupported, but also to raise an exception.  It is a policy rather than a necessity.  One of those things that you can't find from the generated documentation.
